version: '3.2'

services:
  unit_tests:
    build: .

    # We are setting "/usr/src/testdir" as current directory
    # to not manipulate the image contents with testing elements.
    volumes:
      - ./:/usr/src/testdir

    tty: false
    command: >
      sh -c "cd /usr/src/testdir &&
             apk add --update openssl &&
             npm install &&
             npm test"
